[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Intentamos aumentar el timeout al máximo permitido para funciones síncronas
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
